### ISSUE TITLE
New logo for gwallet

### ISSUE THREAD

**Issue by reallinfo** [knocte/gwallet#1]
Hello @knocte I designed a logo for gwallet. how do these look? If you like any of these, I can send you a pr.

![gwalllet](https://user-images.githubusercontent.com/36298335/40008884-2321ece8-57a9-11e8-9968-55b8d450fd0c.jpg)

**Comment by knocte** [comment]
Hey @reallinfo sorry for the super late reply. The logo looks grand! but turns out I was already thinking to rename the wallet.

However, the new name is actually very close to the old one! "geewallet" (I took this one mainly because "gwallet" wasn't available on twitter...) And thinking about it, the way you have finished the "G" part of the icon, to close it like if it was a wallet, seems like a reverse "E", right?

Maybe if you can do a shadow on the E, it would look like two E's. And then we have the desired logo :) Let me know what you think!

**Comment by knocte** [comment]
(Also if by adding the shadow you manage to make the "G" part square-sized instead of rectangular, it would fit better in mobile/desktop-icon scenarios!)

**Comment by knocte** [comment]
Closing because of lack of replies, and anyway we got a new logo now, sorry and thanks!
